# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_v1.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14transaction_v1.proto\x12\x0b\x66inbot.data\"\xba\x04\n\x0bTransaction\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_owner_uuid\x18\n \x01(\t\x12\x1b\n\x13\x61\x63\x63ount_owner_email\x18\x0b \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_uuid\x18\x0c \x01(\t\x12\x15\n\raccount_alias\x18\r \x01(\t\x12.\n\x0c\x61\x63\x63ount_type\x18\x0e \x01(\x0e\x32\x18.finbot.data.AccountType\x12\x14\n\x0c\x61\x63\x63ount_bank\x18\x0f \x01(\t\x12\x18\n\x10\x61\x63\x63ount_currency\x18\x10 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x14 \x01(\t\x12\x12\n\ngdate_time\x18\x15 \x01(\t\x12\x0e\n\x06period\x18\x16 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x17 \x01(\x02\x12*\n\x04type\x18\x18 \x01(\x0e\x32\x1c.finbot.data.TransactionType\x12\x13\n\x0b\x64\x65scription\x18\x19 \x01(\t\x12\x36\n\x10installment_type\x18\x1e \x01(\x0e\x32\x1c.finbot.data.InstallmentType\x12\x13\n\x0binstallment\x18\x1f \x01(\x05\x12\x1a\n\x12total_installments\x18  \x01(\x05\x12\x14\n\x0ctotal_amount\x18! \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18( \x01(\t\x12\x15\n\rsubcategory_1\x18) \x01(\t\x12\x15\n\rsubcategory_2\x18* \x01(\t\x12\x15\n\rsubcategory_3\x18+ \x01(\t*n\n\x0b\x41\x63\x63ountType\x12\t\n\x05OTHER\x10\x00\x12\x0e\n\nDEBIT_CARD\x10\x01\x12\x0f\n\x0b\x43REDIT_CARD\x10\x02\x12\x0b\n\x07SAVINGS\x10\x03\x12\x0e\n\nINVESTMENT\x10\x04\x12\x08\n\x04LOAN\x10\x05\x12\x0c\n\x08\x43HECKING\x10\x06**\n\x0fTransactionType\x12\n\n\x06INCOME\x10\x00\x12\x0b\n\x07\x45XPENSE\x10\x01*+\n\x0fInstallmentType\x12\n\n\x06SINGLE\x10\x00\x12\x0c\n\x08MULTIPLE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACCOUNTTYPE']._serialized_start=610
  _globals['_ACCOUNTTYPE']._serialized_end=720
  _globals['_TRANSACTIONTYPE']._serialized_start=722
  _globals['_TRANSACTIONTYPE']._serialized_end=764
  _globals['_INSTALLMENTTYPE']._serialized_start=766
  _globals['_INSTALLMENTTYPE']._serialized_end=809
  _globals['_TRANSACTION']._serialized_start=38
  _globals['_TRANSACTION']._serialized_end=608
# @@protoc_insertion_point(module_scope)
